
	CREATE DATABASE chat_application;

	USE chat_application;

/*
	CREATE TABLE
----------------------------
*/
/*
	TA_USR : 
		TA_USR_INF : user
		TA_USR_ACCOUNT : account
		TA_USR_TA_USR_FRIENDS : friend
	TA_GROUP :
		TA_GRP_INF : group_chat
		TA_GRP_MEMBERS : group_chat_members
	TA_CON :
		TA_CON_INF : conversation
		TA_CON_FILE : file
	*/
	/*	
		
	USR : user;
	INF : information;
	GRP : group;
	CON : conersation;
	MSG : message;

*/
	
	CREATE TABLE TA_USR_INF (
		I_ID							INT				NOT NULL,
		T_Name 						NVARCHAR(255)	NOT NULL,
		T_Dob							NVARCHAR(255) 	DEFAULT NULL,
		T_PhoneNubmer				NVARCHAR(255) 	DEFAULT NULL,
		T_Email						NVARCHAR(255)	DEFAULT NULL
	);
	
	
	CREATE TABLE TA_USR_ACCOUNT (
		I_ID							INT				NOT NULL,
		I_UserID						INT				NOT NULL,							
		T_UserName	 				VARCHAR(255) 	NOT NULL,
		T_Password					VARCHAR(255)	NOT NULL
	);
	
	CREATE TABLE TA_USR_FRIENDS (
		I_ID 							INT				NOT NULL,
		I_UserID						INT				NOT NULL,
		I_FriendID					INT				NOT NULL,
		I_Status						INT 				DEFAULT 0
	);
	
	-- I_Status mode '0' for requesting, '1' for accepcting
	
	CREATE TABLE TA_GRP_INF (
		I_ID 							INT				NOT NULL,
		T_Name 						NVARCHAR(255) 	NOT NULL
	);
	
	CREATE TABLE TA_GRP_MEMBERS (
		I_ID 							INT				NOT NULL,
		I_GroupID					INT				NOT NULL,
		I_UserID 					INT 				NOT NULL,
		I_Role						INT 				DEFAULT 0
	);
	
	-- I_Role mode '0' for members, '1' for admin group
	
	CREATE TABLE TA_CON_INF (
		I_ID							INT 				NOT NULL,
		I_UserSendID				INT 				NOT NULL,
		I_UserReceiveID			INT				DEFAULT NULL,
		I_GroupReceiveID			INT				DEFAULT NULL,
		T_MessageContent			NVARCHAR(255) 	NOT NULL,
		I_FileInfor					INT				DEFAULT NULL,
		D_SendTime					DATETIME 		DEFAULT NOW()
	);
	
	CREATE TABLE TA_CON_FILE (
		I_ID 							INT				NOT NULL,
		T_FilePath 					VARCHAR(255)	DEFAULT NULL,
		T_FileName					VARCHAR(255)	NOT NULL
	);

/*
	ADD PRIMARY KEY
----------------------------
*/

ALTER TABLE TA_USR_INF
ADD PRIMARY KEY(I_ID);

ALTER TABLE TA_USR_ACCOUNT
ADD PRIMARY KEY(I_ID);

ALTER TABLE TA_USR_FRIENDS
ADD PRIMARY KEY(I_ID);

ALTER TABLE TA_GRP_INF
ADD PRIMARY KEY(I_ID);

ALTER TABLE TA_GRP_MEMBERS
ADD PRIMARY KEY(I_ID);

ALTER TABLE TA_CON_INF
ADD PRIMARY KEY(I_ID);

ALTER TABLE TA_CON_FILE
ADD PRIMARY KEY(I_ID);
		
/*
	SETTING SOME DEFAULT VALUE
----------------------------
*/

ALTER TABLE TA_USR_INF
MODIFY COLUMN I_ID INT AUTO_INCREMENT;

ALTER TABLE TA_USR_ACCOUNT
MODIFY COLUMN I_ID INT AUTO_INCREMENT,
ADD UNIQUE (T_UserName),
ADD UNIQUE (I_UserID);

ALTER TABLE TA_USR_FRIENDS
MODIFY  COLUMN I_ID INT AUTO_INCREMENT;
        

ALTER TABLE TA_GRP_INF
MODIFY COLUMN I_ID INT AUTO_INCREMENT;

ALTER TABLE TA_GRP_MEMBERS
MODIFY COLUMN I_ID INT AUTO_INCREMENT;

ALTER TABLE TA_CON_INF
MODIFY COLUMN I_ID INT AUTO_INCREMENT;

ALTER TABLE TA_CON_FILE
MODIFY COLUMN I_ID INT AUTO_INCREMENT;

/*
	ADD FOREIGN KEY
----------------------------
*/
ALTER TABLE TA_USR_ACCOUNT
ADD FOREIGN KEY (I_UserID) REFERENCES TA_USR_INF(I_ID);

ALTER TABLE TA_GRP_MEMBERS
ADD FOREIGN KEY (I_UserID) REFERENCES TA_USR_INF(I_ID),
ADD FOREIGN KEY (I_GroupID) REFERENCES TA_GRP_INF(I_ID);

ALTER TABLE TA_CON_INF 
ADD FOREIGN KEY (I_UserSendID) REFERENCES TA_USR_INF(I_ID),
ADD FOREIGN KEY (I_UserReceiveID) REFERENCES TA_USR_INF(I_ID),
ADD FOREIGN KEY (I_GroupReceiveID) REFERENCES TA_GRP_INF(I_ID),
ADD FOREIGN KEY (I_FileInfor) REFERENCES  TA_CON_FILE (I_ID);

ALTER TABLE TA_USR_FRIENDS
ADD FOREIGN KEY (I_UserID) REFERENCES TA_USR_INF(I_ID),
ADD FOREIGN KEY (I_FriendID) REFERENCES TA_USR_INF(I_ID);



